fractalClouds.c File Reference
Fractal cloud generator.
#include `fractalCloudsDefs.h`
*
#include <stdio.h>
*
#include <math.h>
*
#include <stdlib.h>
*
#include <time.h>
*
#include <float.h>
*
#include `alloc_funcs.h`
*
#include `dnrutil.h`
*
Functions
Real dgasdev (long *idum)
Real dran1 (long *idum)
void dfourn (Real data[], unsigned long nn[], int ndim, int isign)
void dlfit (Real x[], Real y[], Real sig[], int ndat, Real a[], int ia[], int ma, Real **covar, Real *chisq, void(*funcs)(Real, Real[], int))
short wrap (short i, short n, short m)
Real sed (Real k, Real s)
void poly (Real x, Real pn[], int n)
int main (int argc, char *argv[])
Detailed Description
Fractal cloud generator.
This code generates a single-point log-normal random density field H - via exponentiation of a seed Gaussian random field G - that has a power spectrum $P(k) \propto k^{\beta}$, with $\beta < 0$, with a specified index $1 < |\beta| < 3$. $F$ is the Fourier transform of $H$. It is an implementation of the algorithm by Lewis & Austin (2002), used by, e.g., Sutherland & Bicknell (2003), Sutherland & Bicknell (2007) to generate fractal gas clouds such as the one used by Bland-Hawthorn et al. (2007) and Tepper-Garcia et al. (2015a). For now only available in serial. Note that 1D simulation power spectra are very noisy, since their value at each wavenumber includes at most two contributions. In contrast, 8*(k-1) and 2*(12*(k-1)*(k-1) + 1) values enter into the calculation of the power spectrum at k = 1, 2, ... in 2D and 3D simulations, respectively, and appear therefore smoother than 1D power spectra, even more with increasing k.
Attention
We make use of a number of routines provided by the Numerical Recipes (NR). These have all (and their appropriate arguments) been modified to be of type Real (float or double depending on the user's choice) precision. For this reason, all the NR routine names have been pre-appended with a 'd', i.e. gasdev has been renamed to dgasdev. Also, NR routines adopt the `unit-offset` convention, meaning that the lowest subscript of an array is 1 (rather than 0 as in ANSI C). We use the functions provided by dnrutil to allocate matrices and tensors for consistency with other NR routines.
 Both the Gaussian ad log-normal random field are considered complex (although the imaginary part is set to 0 in the initial Gaussian random field), since their respective Fourier transform will be in general complex. For this reason, we use of the routines dfour1 and dfourn to compute FFT in 1 and 2,3 dimensions, respectively. Note that C does not provide a complex data type, and thus a complex number consists of a pair of real numbers, each member representing the real and imaginary part, respectively.
Compilation (or replace gcc-mp-4.9 by your gcc compiler)
$> gcc-mp-4.9 dnrutil.c dlubksb.c dludcmp.c dsavgol.c dfour1.c dfourn.c dran1.c dgasdev.c dgammln.c dgcf.c dgser.c dgammq.c dfit.c dlfit.c dcovsrt.c dgaussj.c alloc_funcs.c fractalClouds.c -o fractalClouds
Program call
$> ./fractalClouds
Output
All files are simple binary files of type Real (4 or 8 byte depending on the user's choice) per value. For a simulation with dimensionality N=1,2,3 and size DIM, these files are:
gaussNd_ini.bdat: File with the initial Gaussian random field, and it contains $2({\rm DIM})^{\rm N}$ values. Each pair of consecutive values correspond to the real and imaginary part of a complex number representing the value of the field at $x$, $(x,y)$, or $(x,y,z)$ for N=1, 2, or 3, respectively. The values are stored contiguously along the $x$-coordinate, followed by $y$, and $z$.
powSpecNd_<field>#.bdat : Power spectrum $P(k)$ of the <field> = gauss | lognorm, at iteration number #. The file contains DIM numbers, each representing the value of $P(k)$ at $k_n$, where $k_n = n$/DIM, $n = 0, 1, ...,$DIM-1.
searchDirNd_#.bdat : Search direction, i.e., difference between target and current (at iteration number #) power spectrum of log-normal random field. The data structure is the same as powSpecNd_<field>#.bdat.
<field>Nd_filt : Final random field, where <field> = gauss | lognorm. The data structure is the same as gaussNd_ini.bdat.
Accompanying software
plotField.gp: An editable gnuplot script to visualise the result. Edits include setting the dimensionality of the problem, and the field to visualise. Requires gnuplot 4.6 or higher.
Script call:
$> gnuplot plotField.gp
Authors
T.Tepper Garcia (tepper@physics.usyd.edu.au)
Date
Nov 9, 2015
Todo
Todo (!) = URGENT
Encode convergence condition to terminate iteration
Write initial guess for spectral density to disk (binary)
Encapsulate computation of target spectral density into a callable function
Encapsulate computation of power spectrum into a callable function
Encapsulate computation of new spectral density into a callable function
Encapsulate computation of search direction into a callable function
Encapsulate writing of binary files into a callable function
Expand plotField.gp documentation
Parallelise code
Modification history
21 NOV 2016 (TTG): Added binary dump of REAL part of filtered Gaussian / lognormal field
2 DEC 2016 (TTG): Introduced a new parameter (KMIN; minimum wavenumbe) to control the maximum cloudlet size, given by DIM / KMIN
References
Press, W.H. and Teukolsky, S.A. and Vetterling, W.T. and Flannery, B.P., `Numerical Recipes in C`, Cambridge University Press, 1992, Second Edition
Lewis, G. M. and Austin, P. H., `An iterative method for generating scaling log-normal simulations`, Proceedings of the 11th Conference on Atmospheric Radiation, 2002, American Meteorological Society Conference Series 123-126
Sutherland, Ralph S. and Bicknell, Geoffrey V. and Dopita, Michael A., `The Numerical Simulation of Radiative Shocks. II. Thermal Instabilities in Two-dimensional Models`, 2003, The Astrophysical Journal, Volume 591, Number 1, Pages, 238-257
Sutherland, R.S. and Bicknell, G.V., `Interactions of a Light Hypersonic Jet with a Nonuniform Interstellar Medium`, The Astrophysical Journal Supplement, 2007, Volume 173, Pages 37-69
Function Documentation
void dfourn (Real data[], unsigned long nn[], int ndim, int isign)
Replaces data by its ndim-dimensional discrete Fourier transform, if isign is input as 1. nn[1..ndim] is an integer array containing the length of each dimension (number of complex values), which MUST all be powers of 2. data is a real array of length twice the product of these lengths, in which the data are stored as in a multidimensional complex array: real and imaginary parts of each element are in consecutive locations, and the rightmost index of the array increases most rapidly as one proceeds along data. For a two-dimensional array, this is equivalent to storing the array by rows. If isign is input as -1, data is replaced by its inverse transform times the product of the lengths of all dimensions.
Definition at line 5 of file dfourn.c.
Referenced by main().
Real dgasdev (long * idum)
Returns a normally distributed deviate with zero mean and unit variance, using dran1(idum) as the source of uniform deviates.
Definition at line 4 of file dgasdev.c.
References dran1().
Referenced by main().
void dlfit (Real x[], Real y[], Real sig[], int ndat, Real a[], int ia[], int ma, Real ** covar, Real * chisq, void(*)(Real, Real[], int) funcs)
Given a set of data points x[1..ndat], y[1..ndat] with individual standard deviations sig[1..ndat], use $\chi^2$ minimization to fit for some or all of the coefficients a[1..ma] of a function that depends linearly on a, y = sum(ai*afunci(x)). The input array ia[1..ma] indicates by nonzero entries those components of a that should be fitted for, and by zero entries those components that should be held fixed at their input values. The program returns values for a[1..ma], $\chi^2$ = chisq, and the covariance matrix covar[1..ma][1..ma]. (Parameters held fixed will return zero covariances.) The user supplies a routine funcs(x,afunc,ma) that returns the ma basis functions evaluated at x = x in the array afunc[1..ma].
Definition at line 5 of file dlfit.c.
Referenced by main().
Real dran1 (long * idum)
“Minimal” random number generator of Park and Miller with Bays-Durham shuffle and added safeguards. Returns a uniform random deviate between 0.0 and 1.0 (exclusive of the endpoint values). Call with idum a negative integer to initialize; thereafter, do not alter idum between successive deviates in a sequence. RNMX should approximate the largest doubleing value that is less than 1.
Definition at line 13 of file dran1.c.
Referenced by dgasdev().
int main (int argc, char * argv[])
Main Program
Definition at line 143 of file fractalClouds.c.
References dfourn(), dgasdev(), dlfit(), poly(), and sed().
void poly (Real x, Real pn[], int n)
Computes and returns in order in array pn each of the n+1 terms of a polynomial of degree n evaluated at x
Definition at line 3036 of file fractalClouds.c.
Referenced by main().
Real sed (Real k, Real s)
Returns the value of a power-law k^s
Definition at line 3010 of file fractalClouds.c.
Referenced by main().
short wrap (short i, short n, short m)
Calculates the value of index i wrapped-around (to the right) n places on an array of size m
Definition at line 3020 of file fractalClouds.c.